### ISSUE TITLE
failed to open config file for writing

### ISSUE THREAD

**Issue by pico563** [Peterkn2001/DDNS-Updater-with-WiFiManager#1]
@Peterkn2001 
```
16:58:56.134 -> mounting FS...
16:58:56.134 -> failed to mount FS
```

```
17:01:02.369 -> *WM: Sent wifi save page
17:01:04.395 -> *WM: Connecting to new AP
17:01:04.395 -> *WM: Connecting as wifi client...
17:01:08.315 -> *WM: Connection result: 
17:01:08.315 -> *WM: 3
17:01:08.362 -> Should save config
17:01:08.362 -> connected...yeey :)
17:01:08.415 -> saving config
17:01:08.415 -> failed to open config file for writing
```

**Comment by Peterkn2001** [comment]
Looks like the sort of message that WiFiManager gives when you compile the code without allocating any SPIFFS memory.

Pete.

**Comment by pico563** [comment]
@Peterkn2001 
1. you are right. is 64 k SPIFFS enough?
2. why  ` Serial.begin(74880);` and not `115200` ?
3. I added only  2 line after  `server.begin();`  for DuckDNS and it is updating both  now

```
EasyDDNS.service("duckdns");    // Enter your DDNS Service Name - "duckdns" / "noip"
EasyDDNS.client("domain","token");    // Enter ddns Domain & Token | Example - "esp.duckdns.org","1234567"
```
thanks
Joe

**Comment by Peterkn2001** [comment]
1) Yes, you’re only storing a tiny bit of data.
2) I generally use a Wemos D1 Mini, which defaults to 74880, but use whatever is the base baud rate is for your device, so that you can see device boot messages as well as debug messages.
3) I’ve never used DuckDNS, but good to know that you’ve tested it and it works - thanks!

I actually created this because if Brits want to watch UK catchup TV in foreign countries they have to use a GeoIP blocking service. I don’t like VPN services, and the SmartDNSProxy.com service is much better as it allows more control. The only downside to SmartDNSProxy is that you have to log in to their website to update your public IP every time it changes. The workaround is to have SmartDNSProxy updated via a DDNS account, so you need a simple DDNS updater.

I pop the firmware on one of these:
https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.co.uk%2Fulk%2Fitm%2F223044742649
which is basically a NodeMCU in a USB stick, with none of the pins accessible. It’s a simple solution for anybody who just wants to plug it in, configure the settings via the WiFiManager captive portal, and forget it.

Pete.
